### ISSUE TITLE
elfshaker clone fails when server does not return Content-Length

### ISSUE THREAD

**Issue by Mistuke** [elfshaker/elfshaker#104]
When cloning from a server, the server can either return `Content-Length` or `Transfer-Encoding`. 

However elfshaker doesn't handle the latter case correctly because it tries to draw a progress bar which of course fails when there's no `Content-Length`:

```
thread 'main' panicked at 'assertion failed: (0..=100).contains(&percent_complete)', src/bin/elfshaker/utils.rs:130:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:115:5
   3: elfshaker::utils::create_progress_bar
   4: elfshaker::utils::create_percentage_print_reporter::{{closure}}
   5: std::io::Write::write_all
   6: std::io::copy::stack_buffer_copy
   7: elfshaker::repo::remote::update_remote_pack
   8: elfshaker::repo::repository::Repository::update_remote_pack
   9: elfshaker::repo::repository::Repository::extract_entries
  10: elfshaker::repo::repository::Repository::extract_snapshot
  11: elfshaker::extract::run
  12: elfshaker::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I've hacked up the source code to just not draw the progress bar when `Content-Length` is `0` which gets it to work correctly. But it's just a hack.

**Comment by Mistuke** [comment]
I suggest storing the filesize in the `esi` file as well. when the server doesn't send back `Content-Length` we can use that size instead.

when the server does send back a `Content-Length` the two should match, and the final downloaded binary should match the original size.

If maintainers agree I can implement this.

**Comment by peterwaller-arm** [comment]
Uh, storing the size inside the file could modify its size? It seems to me you would really want that information to exist out-of-band.

But also the esi is tiny, so having a progress bar for downloading it doesn't seem terribly important to me - we should gracefully fall back to showing a spinner if we don't know the size.

**Comment by Mistuke** [comment]
Hmm? What do you mean? The esi stores the link to the index and the package itself, including their hashes.

The issue isn't with showing a progress for the esi file, but that for downloading the packages.  So I don't get how adding a field to the esi to show the sizes (along side the hashes) would change anything on the packages themselves, if it did the hashes would also be broken :)

for the esi file download itself I don't see any progress bar code.

**Comment by veselink1** [comment]
`ProgressWriter::new` does not require the size to be specified. I suggest we use that and avoid changing the .esi format.

**Comment by peterwaller-arm** [comment]
Ah, apologies @Mistuke, from our previous offline conversation I somehow mistakenly came to think we were crashing on the esi file itself rather than the packs, but I see from the stack trace in this issue that this is happening to the packs themselves.

I think the priority should be on not crashing, followed by niceties such as showing an accurate progress bar. I would prefer not to have different esi formats floating around unless it's unavoidable.

So my preferences are:
* First don't crash.
* If we can't show the expected amount, at least show the amount downloaded.
* Via some other means, determine the amount. But we should discuss and think hard before having multiple esi formats floating around.
