### ISSUE TITLE
Panic: leaf_dir cannot be the same directory as boundary_dir

### ISSUE THREAD

**Issue by peterwaller-arm** [elfshaker/elfshaker#73]
Not yet had time to investigate.

My workflow is that I came back to a `manyclangs` directory I had been using after some time, and when I tried to do `elfshaker extract <a much older snapshot`, I see the following panic.

It seems to be straightforward to reproduce by switching between recent snapshots, but I haven't yet found my way to a cause.

```
thread 'main' panicked at 'leaf_dir cannot be the same directory as boundary_dir', src/repo/fs.rs:122:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'leaf_dir cannot be the same directory as boundary_dir', src/repo/fs.rs:122:5
stack backtrace:
   0:     0xaaaae3d0842c - std::backtrace_rs::backtrace::libunwind::trace::h3532d9a57d8c674f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaae3d0842c - std::backtrace_rs::backtrace::trace_unsynchronized::h6081142ce80fb15a
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaae3d0842c - std::sys_common::backtrace::_print_fmt::hf70d8eba9e92197d
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xaaaae3d0842c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4a6fd4d7415dc3d4
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:46:22
   4:     0xaaaae3d28ea4 - core::fmt::write::h06ba04742f884535
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/fmt/mod.rs:1168:17
   5:     0xaaaae3d04408 - std::io::Write::write_fmt::hb2e86a664318ca6c
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/io/mod.rs:1660:15
   6:     0xaaaae3d0adbc - std::sys_common::backtrace::_print::h57c271a64ddf60a0
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:49:5
   7:     0xaaaae3d0adbc - std::sys_common::backtrace::print::he2782ac04eea0775
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/sys_common/backtrace.rs:36:9
   8:     0xaaaae3d0adbc - std::panicking::default_hook::{{closure}}::hfe7e72928cc27619
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:211:50
   9:     0xaaaae3d0a930 - std::panicking::default_hook::h9f617c0c494e5c2f
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:228:9
  10:     0xaaaae3d0b3d4 - std::panicking::rust_panic_with_hook::h12e8ba58cca24a37
                               at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:610:17
  11:     0xaaaae3bc0440 - std::panicking::begin_panic::{{closure}}::ha09f140f470eba75
  12:     0xaaaae3bc0400 - std::sys_common::backtrace::__rust_end_short_backtrace::ha0665ffddf715667
  13:     0xaaaae3b6551c - std::panicking::begin_panic::h6d3a45d6a7961313
  14:     0xaaaae3bb6d68 - elfshaker::repo::fs::EmptyDirectoryCleanupQueue::process::h0a75332c37df7135
  15:     0xaaaae3b99a58 - core::ptr::drop_in_place<elfshaker::repo::fs::EmptyDirectoryCleanupQueue>::h60fc702de5b3c3c0
  16:     0xaaaae3b9cba8 - elfshaker::repo::repository::Repository::extract_snapshot::ha8749e9e049cd5c5
  17:     0xaaaae3b86704 - elfshaker::extract::run::hc57938c8dd4835d6
  18:     0xaaaae3b89d74 - elfshaker::main::had41a90d158806a7
```

**Comment by veselink1** [comment]
I think this panic was removed in https://github.com/elfshaker/elfshaker/commit/fc37d64491db142ee747ebe69bee03bd11ae3df4. Do you see it happen with a fresh build of master?

**Comment by peterwaller-arm** [comment]
Indeed that seems to work, sorry I missed that somehow, thanks!
